import { Post } from "@/types/instagram";

export const SEED_POSTS: Post[] = [
  {
    id: "1",
    caption:
      "Behind the scenes of our latest product shoot ✨ The team worked incredibly hard to make this one happen. Can't wait to share the final result with all of you! Stay tuned for the big reveal this Friday. #BTS #ProductShoot #ComingSoon",
    postType: "carousel",
    status: "scheduled",
    scheduledDate: "2026-04-02T10:00",
    mediaNote: "5-slide carousel: studio setup, props, lighting rig, team candid, final shot",
    tags: ["bts", "product", "launch"],
    createdAt: "2026-03-28T09:00:00Z",
  },
  {
    id: "2",
    caption:
      "Good morning from the studio 🌅 Starting the week off with fresh ideas and strong coffee. What are you working on this week? Drop it in the comments 👇",
    postType: "photo",
    status: "scheduled",
    scheduledDate: "2026-04-04T08:30",
    mediaNote: "Flat lay of desk setup with coffee and notebook",
    tags: ["monday", "motivation", "studio"],
    createdAt: "2026-03-29T11:00:00Z",
  },
  {
    id: "3",
    caption:
      "Quick tutorial: 3 ways to style our signature piece for different occasions 🎨 From casual to evening-ready in under 60 seconds.",
    postType: "reel",
    status: "scheduled",
    scheduledDate: "2026-04-06T17:00",
    mediaNote: "30s reel, 3 outfit transitions, upbeat music",
    tags: ["tutorial", "style", "reel"],
    createdAt: "2026-03-27T14:30:00Z",
  },
  {
    id: "4",
    caption:
      "The story behind our brand — how it all started in a small apartment with a big dream. Read the full story on our blog (link in bio).",
    postType: "photo",
    status: "draft",
    mediaNote: "Founder portrait, original workspace photo",
    tags: ["brand", "story", "founders"],
    createdAt: "2026-03-25T16:00:00Z",
  },
  {
    id: "5",
    caption: "New collection drops April 15th. Are you ready? 👀 #NewCollection #SpringDrop",
    postType: "video",
    status: "draft",
    mediaNote: "30s teaser video, slow motion product reveal",
    tags: ["newcollection", "spring", "teaser"],
    createdAt: "2026-03-24T10:00:00Z",
  },
  {
    id: "6",
    caption:
      "5 things we wish we knew before starting our business 💡\n\n1. Community comes first\n2. Be consistent, not perfect\n3. Your niche will find you\n4. Invest in good photography\n5. Build in public\n\nSave this for later! 🔖",
    postType: "carousel",
    status: "draft",
    mediaNote: "6 slides: cover + one slide per tip, clean typographic design",
    tags: ["tips", "business", "entrepreneur"],
    createdAt: "2026-03-22T09:00:00Z",
  },
  {
    id: "7",
    caption:
      "Our best month yet 🎉 So grateful for every single one of you who has supported us on this journey. Here's to more milestones ahead! 🥂",
    postType: "photo",
    status: "published",
    scheduledDate: "2026-03-20T12:00",
    mediaNote: "Celebration flat lay, confetti and champagne",
    tags: ["milestone", "gratitude", "community"],
    createdAt: "2026-03-18T11:00:00Z",
  },
  {
    id: "8",
    caption:
      "We asked, you answered 📊 Here are the results from last week's poll. Looks like you're all team reel! More coming soon 🎬",
    postType: "photo",
    status: "published",
    scheduledDate: "2026-03-18T10:00",
    mediaNote: "Screenshot of poll results with branded overlay",
    tags: ["community", "poll", "results"],
    createdAt: "2026-03-16T09:00:00Z",
  },
  {
    id: "9",
    caption: "Day in the life at the studio 🎬 Follow along as we prep for our biggest shoot of the year.",
    postType: "story",
    status: "published",
    scheduledDate: "2026-03-15T09:00",
    mediaNote: "3-part story series, vertical format",
    tags: ["dayinthelife", "studio", "vlog"],
    createdAt: "2026-03-14T08:00:00Z",
  },
  {
    id: "10",
    caption: "Collab idea with @partner — co-authored giveaway post. Need to align on prize details and copy before finalizing.",
    postType: "photo",
    status: "backlog",
    mediaNote: "Joint product photo, both brands visible",
    tags: ["collab", "giveaway", "partnership"],
    createdAt: "2026-03-20T14:00:00Z",
  },
  {
    id: "11",
    caption: "Customer spotlight series — feature weekly customers sharing their experience with our product.",
    postType: "carousel",
    status: "backlog",
    mediaNote: "UGC photos from customers, 4-slide carousel template",
    tags: ["ugc", "customerspot", "community"],
    createdAt: "2026-03-19T10:00:00Z",
  },
  {
    id: "12",
    caption: "Holiday campaign concept: 12 days of content leading up to the summer launch. Each day teases a different product.",
    postType: "reel",
    status: "backlog",
    mediaNote: "Series of 12 short reels, unified visual identity",
    tags: ["campaign", "summer", "launch"],
    createdAt: "2026-03-17T15:00:00Z",
  },
];
